// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-m-KgxhD0LzAldu1ZvbMAHaWyeaBnFw8',
    appId: '1:227117753015:web:e7b8b5adc1829434aba332',
    messagingSenderId: '227117753015',
    projectId: 'fixmatesflutter',
    authDomain: 'fixmatesflutter.firebaseapp.com',
    storageBucket: 'fixmatesflutter.appspot.com',
    measurementId: 'G-HFEWK7NS62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7-m4YsMBnx99TjozbO0g8O6ihnARvMhQ',
    appId: '1:227117753015:android:22a974a01dce653daba332',
    messagingSenderId: '227117753015',
    projectId: 'fixmatesflutter',
    storageBucket: 'fixmatesflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZSKNh5Q3ovESZHlBBktrPXa8BN3WNkjE',
    appId: '1:227117753015:ios:6d467ed064f246a2aba332',
    messagingSenderId: '227117753015',
    projectId: 'fixmatesflutter',
    storageBucket: 'fixmatesflutter.appspot.com',
    iosBundleId: 'com.example.fixMatesUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZSKNh5Q3ovESZHlBBktrPXa8BN3WNkjE',
    appId: '1:227117753015:ios:6d467ed064f246a2aba332',
    messagingSenderId: '227117753015',
    projectId: 'fixmatesflutter',
    storageBucket: 'fixmatesflutter.appspot.com',
    iosBundleId: 'com.example.fixMatesUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-m-KgxhD0LzAldu1ZvbMAHaWyeaBnFw8',
    appId: '1:227117753015:web:c9f3c22017365e3daba332',
    messagingSenderId: '227117753015',
    projectId: 'fixmatesflutter',
    authDomain: 'fixmatesflutter.firebaseapp.com',
    storageBucket: 'fixmatesflutter.appspot.com',
    measurementId: 'G-HDFM6ET6Y0',
  );
}
